app = "feedback-s"
primary_region = "ams"

[build]
  build_command = "npm install --include=dev && npm run prisma:migrate && npm run build"

[deploy]
  release_command = "npx prisma migrate deploy"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 8080
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "npm run start"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 256